version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - ./ddl_constructor.sql ./ddl_constructor.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
      - "5433:5433"
