--- 
- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-server
    - python3-devel
    - postgresql-libs
    - postgresql-devel
    - python-psycopg2

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists
 
- name: "Start and enable services"
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - postgresql

- name: "Allow md5 connection for the db user"
  shell: "echo 'hostall             all             0.0.0.0/0            md5' >> /var/lib/pgsql/data/pg_hba.conf"
  become: yes
  become_user: postgres

- name: "Allow listen_address = *"
  shell: "echo `listen_addresses = '*'` >> /var/lib/pgsql/data/postgresql.conf"
  become: yes
  become_user: postgres

- name: "Restart postgres"
  service:
    name: postgresql
    state: restarted
    enabled: yes
  become_user: postgres
